In [1]:
sys.path.append("../..")
from thesis.envs.matrix_routing_zoo_cyclic import MatrixRoutingMACyclic, ZooToVec_PRE, ZooToVec_POST
from alpyne.client.alpyne_client import AlpyneClient
import supersuit as ss
from stable_baselines3.common.vec_env.dummy_vec_env import DummyVecEnv
from stable_baselines3.common.monitor import Monitor

KeyboardInterrupt: 

In [ ]:
#client = AlpyneClient("../../envs/MiniMatrix.zip", port = 51149)
pre = Monitor(ZooToVec_PRE(MatrixRoutingMACyclic(model_path = "../../envs/MiniMatrix.zip", fleetsize = 2, max_fleetsize = 3, max_seconds = 60, port=51149)))

c:\Users\Wegma\.conda\envs\thesis\lib\site-packages\alpyne\client\utils.py:124: UserWarning: Unzipping to temporary directory (C:\Users\Wegma\AppData\Local\Temp\alpyne_73904_n3t1obko)
  warn(f"Unzipping to temporary directory ({tmp_dir})")


In [ ]:
post=ZooToVec_POST(pre)

In [ ]:
post.envs[0].get_episode_rewards()

[]

In [ ]:
post.reset()
post.step([0,1])

[False False]
[{}, {}]


(array([[1.        , 1.        , 1.        , 0.7909091 , 0.7209302 ,
         0.7909091 , 0.7209302 , 0.7613636 , 0.88372093, 0.        ,
         0.        , 0.        , 1.        , 1.        , 0.54545456,
         0.88372093, 0.47727272, 0.88372093, 0.8181818 , 1.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [1.        , 1.        , 1.        , 0.54545456, 0.88372093,
         0.47727272, 0.88372093, 0.8181818 , 1.        , 0.        ,
         0.        , 0.        , 1.        , 1.        , 0.7909091 ,
         0.7209302 , 0.7909091 , 0.7209302 , 0.7613636 , 0.88372093,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ]], dtype=float32),
 array([0., 0.]),
 array([False, False]),
 [{}, {}])

In [ ]:
from stable_baselines3 import PPO

model = PPO("MlpPolicy", post)

tensor([0, 1], dtype=torch.int32)

In [ ]:
from torch import nn
import torch
nn.Embedding(10, 5)._parameters

OrderedDict([('weight',
              Parameter containing:
              tensor([[ 0.5228,  0.5456, -0.6573,  0.3797,  0.8935],
                      [-0.7007,  0.8040, -0.3753,  0.3442,  0.8728],
                      [-0.2060, -0.2201,  0.5950,  0.5286, -0.9690],
                      [ 1.1792, -1.9931,  0.6682,  0.8160, -1.5218],
                      [-0.6646, -0.0600, -0.2445,  0.5152, -0.2113],
                      [ 1.9150,  1.9093, -1.0472, -1.7514, -1.1269],
                      [-0.0480, -0.3420, -0.7212, -0.4172, -1.1058],
                      [-0.5137,  0.8983,  0.6173, -1.3824,  2.1602],
                      [ 0.3740,  1.1850, -0.8580, -0.6287,  0.7872],
                      [ 1.0354,  0.0187, -1.7093, -0.4344,  0.1074]], requires_grad=True))])

In [ ]:
test = torch.tensor([[0.1, 0.2], [0.3, 0.2], [0.7, 0.7]])

In [ ]:
a = torch.Tensor([[0.3, 0.203], [0.7, 0.203]])

In [ ]:
range = torch.arange(0, len(test)).repeat(len(a),1)
no = - torch.ones_like(range)

In [ ]:
sys.path.append("../..")
from thesis.policies.routing_attention import Nodewise_Embedder

In [ ]:
em = Nodewise_Embedder(not_node_obs=3, node_len=2, embed_len=10, n_nodes=30)

In [ ]:
torch.rand(1,1,5).to(dtype=torch.int32)

tensor([[[0, 0, 0, 0, 0]]], dtype=torch.int32)

In [ ]:
em(torch.rand(1,1,17))

RuntimeError: shape '[1, 10]' is invalid for input of size 70

In [ ]:
not []

True

In [ ]:
torch.multiply([0,1,2,3])

TypeError: multiply() received an invalid combination of arguments - got (list), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other)


In [ ]:
test.shape

torch.Size([3, 2])

In [ ]:
a2 = a[:,None, :].repeat(1,test.shape[0],1)

In [ ]:
t2 = test.repeat(len(a),1,1)

In [ ]:
torch.all(torch.isclose(t2, a2, 0.1), axis = 2)

tensor([[False,  True, False],
        [False, False, False]])

In [ ]:
torch.max(torch.where(torch.all(torch.isclose(t2, a2, 0.1), axis=2), range, no), axis = 1)[0]

tensor([ 1, -1])

In [ ]:
model.learn(10000)

[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[False False]
[{}, {}]
[ True  True]
[{'terminal_observation': array([1.        , 1.        , 1.        , 0.54545456, 1.        ,
       0.54545456, 1.        , 0.7909091 , 0.7209302 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.    

KeyboardInterrupt: 

In [ ]:
model.env.envs[0].env.envs[0].rewards

{'0': 0.0, '1': 0.0}