In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

In [4]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
num_episodes = 30000
max_steps_per_episode = 100

learning_rate = 0.1     #Alpha
discount_rate = 0.99    #Gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [6]:
rewards_all_episodes = []

In [7]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break        

    # Exploration rate decay   
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
        
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), len(rewards_all_episodes)/1000)
count = 1000
print("*******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n*******Q-table*******\n")
print(q_table)

*******Average reward per thousand episodes*******

1000 :  0.05400000000000004
2000 :  0.20500000000000015
3000 :  0.4140000000000003
4000 :  0.5630000000000004
5000 :  0.6040000000000004
6000 :  0.6450000000000005
7000 :  0.7040000000000005
8000 :  0.6750000000000005
9000 :  0.6600000000000005
10000 :  0.6890000000000005
11000 :  0.6960000000000005
12000 :  0.6650000000000005
13000 :  0.6860000000000005
14000 :  0.6810000000000005
15000 :  0.6920000000000005
16000 :  0.6670000000000005
17000 :  0.7040000000000005
18000 :  0.6570000000000005
19000 :  0.6820000000000005
20000 :  0.7080000000000005
21000 :  0.6840000000000005
22000 :  0.6550000000000005
23000 :  0.6870000000000005
24000 :  0.6620000000000005
25000 :  0.6920000000000005
26000 :  0.6650000000000005
27000 :  0.6740000000000005
28000 :  0.6900000000000005
29000 :  0.6540000000000005
30000 :  0.6740000000000005


*******Q-table*******

[[0.58554903 0.51799719 0.50332643 0.51810293]
 [0.32222344 0.28547468 0.35813997 0.505378

In [9]:
env.reset()

0

In [15]:
env.step(1)

(4, 0.0, False, {'prob': 0.3333333333333333})

In [7]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    print("*******EPISODE", episode + 1, "*******\n\n\n\n")
    time.sleep(1)
    #rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])   
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("*******Your reached the Goal!*******")
                time.sleep(3)
            else:
                print("*******You fell through a hole!*******")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
                
        
env.close()

*******Your reached the Goal!*******
