In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1     #Alpha
discount_rate = 0.99    #Gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes = []

In [6]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break        

    # Exploration rate decay   
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
        
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), len(rewards_all_episodes)/1000)
count = 1000
print("*******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n*******Q-table*******\n")
print(q_table)

*******Average reward per thousand episodes*******

1000 :  0.036000000000000025
2000 :  0.21600000000000016
3000 :  0.3990000000000003
4000 :  0.5900000000000004
5000 :  0.6220000000000004
6000 :  0.6680000000000005
7000 :  0.6450000000000005
8000 :  0.6630000000000005
9000 :  0.6780000000000005
10000 :  0.6700000000000005


*******Q-table*******

[[0.51796606 0.49053466 0.48826511 0.48138336]
 [0.20343237 0.26804977 0.33294568 0.44086724]
 [0.38880291 0.26292686 0.2614279  0.27305411]
 [0.05510591 0.10831792 0.01786634 0.20731709]
 [0.54141159 0.33294311 0.42470014 0.37820403]
 [0.         0.         0.         0.        ]
 [0.1431405  0.17807606 0.32673142 0.12770799]
 [0.         0.         0.         0.        ]
 [0.43029515 0.33556319 0.38074271 0.58217947]
 [0.56005641 0.61734446 0.32947125 0.21963548]
 [0.66857885 0.41801393 0.23910848 0.29398867]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.39989983 0.53978524 0.75358987 0.4

In [7]:
env.reset()

0

In [8]:
env.step(1)

(4, 0.0, False, {'prob': 0.3333333333333333})

In [9]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    print("*******EPISODE", episode + 1, "*******\n\n\n\n")
    time.sleep(1)
    #rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])   
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("*******Your reached the Goal!*******")
                time.sleep(3)
            else:
                print("*******You fell through a hole!*******")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
                
        
env.close()

  (Left)
SFFF
FHFH
FFFH
HFFG


KeyboardInterrupt: 