In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v1")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1     #Alpha
discount_rate = 0.99    #Gamma

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [5]:
rewards_all_episodes = []

In [6]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        # Update Q-table
        q_table[state, action] = q_table[state, action] * (1-learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break        

    # Exploration rate decay   
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate * episode)
        
    # Add current episode reward to total rewards list
    rewards_all_episodes.append(rewards_current_episode)
    
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes), len(rewards_all_episodes)/1000)
count = 1000
print("*******Average reward per thousand episodes*******\n")
for r in rewards_per_thousand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
    
print("\n\n*******Q-table*******\n")
print(q_table)

*******Average reward per thousand episodes*******

1000 :  0.05000000000000004
2000 :  0.19500000000000015
3000 :  0.4130000000000003
4000 :  0.5780000000000004
5000 :  0.6120000000000004
6000 :  0.6370000000000005
7000 :  0.7050000000000005
8000 :  0.6650000000000005
9000 :  0.6970000000000005
10000 :  0.6700000000000005


*******Q-table*******

[[0.55451366 0.51504465 0.53979929 0.54327559]
 [0.38235147 0.32512458 0.26388175 0.53007163]
 [0.40264283 0.41918091 0.41802062 0.50455001]
 [0.32355197 0.33884337 0.36738974 0.48053912]
 [0.57239754 0.29480761 0.49481673 0.39639096]
 [0.         0.         0.         0.        ]
 [0.13768892 0.13816423 0.25824789 0.09287859]
 [0.         0.         0.         0.        ]
 [0.49906136 0.44386199 0.50002976 0.60016807]
 [0.26899321 0.61561851 0.43843825 0.28785107]
 [0.49777401 0.39905915 0.37626756 0.35468474]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.50359804 0.58834145 0.72009198 0.51

In [7]:
env.reset()

0

In [8]:
env.step(1)

(4, 0.0, False, {'prob': 0.3333333333333333})

In [9]:
# Q-learning algorithm
for episode in range(num_episodes):
    state = env.reset()
    done = False
    print("*******EPISODE", episode + 1, "*******\n\n\n\n")
    time.sleep(1)
    #rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state, :])   
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("*******Your reached the Goal!*******")
                time.sleep(3)
            else:
                print("*******You fell through a hole!*******")
                time.sleep(3)
            clear_output(wait=True)
            break
        state = new_state
                
        
env.close()

KeyboardInterrupt: 